# Generated by Django 3.2.9 on 2022-01-02 21:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_information',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='飲食店ID')),
                ('restaurant_name', models.CharField(max_length=50, verbose_name='飲食店名')),
                ('explanation', models.TextField(max_length=1000, verbose_name='説明文')),
                ('tel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('address', models.TextField(max_length=100, verbose_name='住所')),
                ('transportation', models.TextField(max_length=100, verbose_name='アクセス')),
                ('time', models.TextField(max_length=100, verbose_name='営業時間')),
                ('budget', models.TextField(max_length=50, verbose_name='予算')),
                ('payment', models.TextField(max_length=100, verbose_name='支払方法')),
                ('seat', models.CharField(blank=True, max_length=20, verbose_name='席')),
                ('private_room', models.CharField(blank=True, max_length=20, verbose_name='個室')),
                ('reserved', models.CharField(blank=True, max_length=20, verbose_name='貸切')),
                ('smoking', models.CharField(blank=True, max_length=20, verbose_name='禁煙&喫煙')),
                ('parking', models.CharField(blank=True, max_length=20, verbose_name='駐車場')),
                ('equipment', models.TextField(blank=True, max_length=50, verbose_name='空間&設備')),
                ('menu', models.TextField(blank=True, max_length=255, verbose_name='メニュー')),
                ('cooking', models.TextField(blank=True, max_length=255, verbose_name='料理')),
                ('course', models.TextField(blank=True, max_length=255, verbose_name='コース')),
                ('use_scene', models.TextField(blank=True, max_length=255, verbose_name='利用シーン')),
                ('location', models.TextField(blank=True, max_length=255, verbose_name='ロケーション')),
                ('service', models.TextField(blank=True, max_length=500, verbose_name='サービス')),
                ('children', models.TextField(blank=True, max_length=255, verbose_name='お子様連れ')),
                ('dress_code', models.TextField(blank=True, max_length=100, verbose_name='ドレスコード')),
                ('remarks', models.TextField(blank=True, max_length=1000, verbose_name='備考')),
                ('restaurant_allergy', models.TextField(blank=True, max_length=1000, verbose_name='アレルギー')),
                ('tags', models.TextField(blank=True, max_length=500, verbose_name='タグ')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_information')),
            ],
        ),
        migrations.CreateModel(
            name='store_menu',
            fields=[
                ('menu_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='メニューID')),
                ('name', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('allergy', models.CharField(blank=True, max_length=100, verbose_name='アレルギー')),
                ('remarks', models.TextField(blank=True, max_length=300, verbose_name='備考')),
                ('price', models.IntegerField(verbose_name='値段')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.store_information')),
            ],
        ),
        migrations.CreateModel(
            name='store_images',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='画像ID')),
                ('image', models.ImageField(upload_to='images')),
                ('attribute', models.CharField(max_length=20, verbose_name='属性')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.store_information')),
            ],
        ),
    ]
