# Generated by Django 3.2.9 on 2022-01-14 01:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant_information',
            fields=[
                ('restaurant_id', models.CharField(default=restaurants.models.restaurant_information.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='飲食店ID')),
                ('restaurant_name', models.CharField(max_length=50, verbose_name='飲食店名')),
                ('explanation', models.TextField(max_length=1000, verbose_name='説明文')),
                ('tel', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('address', models.TextField(max_length=100, verbose_name='住所')),
                ('transportation', models.TextField(max_length=100, verbose_name='アクセス')),
                ('time', models.TextField(max_length=100, verbose_name='営業時間')),
                ('budget', models.TextField(max_length=50, verbose_name='予算')),
                ('payment', models.TextField(max_length=100, verbose_name='支払方法')),
                ('seat', models.CharField(blank=True, max_length=20, verbose_name='席')),
                ('private_room', models.CharField(blank=True, max_length=20, verbose_name='個室')),
                ('reserved', models.CharField(blank=True, max_length=20, verbose_name='貸切')),
                ('smoking', models.CharField(blank=True, max_length=20, verbose_name='禁煙&喫煙')),
                ('parking', models.CharField(blank=True, max_length=20, verbose_name='駐車場')),
                ('equipment', models.TextField(blank=True, max_length=50, verbose_name='空間&設備')),
                ('menu', models.TextField(blank=True, max_length=255, verbose_name='メニュー')),
                ('cooking', models.TextField(blank=True, max_length=255, verbose_name='料理')),
                ('course', models.TextField(blank=True, max_length=255, verbose_name='コース')),
                ('use_scene', models.TextField(blank=True, max_length=255, verbose_name='利用シーン')),
                ('location', models.TextField(blank=True, max_length=255, verbose_name='ロケーション')),
                ('service', models.TextField(blank=True, max_length=500, verbose_name='サービス')),
                ('children', models.TextField(blank=True, max_length=255, verbose_name='お子様連れ')),
                ('dress_code', models.TextField(blank=True, max_length=100, verbose_name='ドレスコード')),
                ('remarks', models.TextField(blank=True, max_length=1000, verbose_name='備考')),
                ('restaurant_allergy', models.TextField(blank=True, max_length=1000, verbose_name='アレルギー')),
                ('tags', models.TextField(blank=True, max_length=500, verbose_name='タグ')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_information')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.CharField(default=restaurants.models.review.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='レビューID')),
                ('review', models.TextField(blank=True, max_length=500, verbose_name='レビュー')),
                ('image', models.ImageField(upload_to='review', verbose_name='画像')),
                ('evaluation', models.IntegerField(verbose_name='評価')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant_information')),
            ],
        ),
        migrations.CreateModel(
            name='menus',
            fields=[
                ('menu_id', models.CharField(default=restaurants.models.menus.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='メニューID')),
                ('name', models.CharField(max_length=50, verbose_name='メニュー名')),
                ('image', models.ImageField(upload_to='menu', verbose_name='画像')),
                ('allergy', models.CharField(blank=True, max_length=100, verbose_name='アレルギー')),
                ('remarks', models.TextField(blank=True, max_length=300, verbose_name='備考')),
                ('price', models.IntegerField(verbose_name='値段')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant_information')),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('image_id', models.CharField(default=restaurants.models.images.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='画像ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='画像')),
                ('attribute', models.CharField(choices=[('exterior', 'お店の外観'), ('introspection', 'お店の内観'), ('seat', '席'), ('Kitchen', '調理場'), ('cooking', '料理'), ('others', 'その他')], max_length=20, verbose_name='属性')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant_information')),
            ],
        ),
        migrations.CreateModel(
            name='customer_question',
            fields=[
                ('question_id', models.CharField(default=restaurants.models.customer_question.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='質問ID')),
                ('question', models.TextField(blank=True, max_length=400, verbose_name='質問')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant_information')),
            ],
        ),
        migrations.CreateModel(
            name='customer_answer',
            fields=[
                ('answer_id', models.CharField(default=restaurants.models.customer_answer.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='回答ID')),
                ('answer', models.TextField(blank=True, max_length=400, verbose_name='回答')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.customer_question')),
            ],
        ),
    ]
