# Generated by Django 3.2.9 on 2022-01-13 05:57

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_answer',
            name='answer_id',
            field=models.CharField(default=restaurants.models.customer_answer.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='回答ID'),
        ),
        migrations.AlterField(
            model_name='customer_question',
            name='question_id',
            field=models.CharField(default=restaurants.models.customer_question.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='質問ID'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_id',
            field=models.CharField(default=restaurants.models.images.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='画像ID'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='menu_id',
            field=models.CharField(default=restaurants.models.menus.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='メニューID'),
        ),
        migrations.AlterField(
            model_name='restaurant_information',
            name='restaurant_id',
            field=models.CharField(default=restaurants.models.restaurant_information.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='飲食店ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(default=restaurants.models.review.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='レビューID'),
        ),
    ]
