# Generated by Django 3.2.9 on 2022-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_images',
            name='attribute',
            field=models.CharField(choices=[('exterior', 'お店の外観'), ('introspection', 'お店の内観'), ('seat', '席'), ('Kitchen', '調理場'), ('cooking', '料理'), ('others', 'その他')], max_length=20, verbose_name='属性'),
        ),
    ]
