# Generated by Django 3.2.9 on 2021-12-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_images',
            name='store',
        ),
    ]
