# Generated by Django 3.2.9 on 2022-01-10 12:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_store_images_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_menu',
            name='image',
            field=models.ImageField(default='', upload_to='menu', verbose_name='画像'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store_images',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='画像'),
        ),
        migrations.CreateModel(
            name='store_review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='レビューID')),
                ('review', models.TextField(blank=True, max_length=500, verbose_name='レビュー')),
                ('image', models.ImageField(upload_to='review', verbose_name='画像')),
                ('evaluation', models.IntegerField(verbose_name='評価')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.store_information')),
            ],
        ),
    ]
