# Generated by Django 3.2.9 on 2022-01-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20220117_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy_tags',
            name='image',
            field=models.ImageField(default='', upload_to='allergy', verbose_name='画像'),
            preserve_default=False,
        ),
    ]
