# Generated by Django 3.2.9 on 2021-12-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_store_images_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_images',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
