# Generated by Django 3.2.9 on 2022-01-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20220118_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
