# Generated by Django 3.2.9 on 2022-01-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='allergy',
        ),
        migrations.AddField(
            model_name='menus',
            name='allergy_tag',
            field=models.ManyToManyField(to='restaurants.allergy_tags'),
        ),
        migrations.AlterField(
            model_name='restaurant_information',
            name='allergy_tag',
            field=models.ManyToManyField(to='restaurants.allergy_tags'),
        ),
    ]
