# Generated by Django 3.2.9 on 2022-01-13 05:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='user_id',
            field=models.CharField(default=accounts.models.user_information.get_uuid_no_dash, editable=False, max_length=33, primary_key=True, serialize=False, unique=True, verbose_name='ユーザーID'),
        ),
    ]
